---
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/global-service: "true"
  labels:
    app.kubernetes.io/name: cluster-info
  name: cluster-info
spec:
  selector:
    app.kubernetes.io/name: cluster-info
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cluster-info
  name: cluster-info
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-info
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cluster-info
    spec:
      containers:
      - name: cluster-info
        image: hashicorp/http-echo
        args:
        - -listen
        - :80
        - -text
        - Hello from 'kind-cilium-mesh-2/$(POD_NAME)'
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: http