apiVersion: v1
kind: Service
metadata:
  # labels:
  #   app: my-replica-set-0-svc
  # name: my-replica-set-0-svc
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  publishNotReadyAddresses: true
  selector:
    # app: my-replica-set-0