---
apiVersion: v1
kind: Service
metadata:
  name: cilium-etcd-external
  namespace: kube-system
spec:
  ports:
  - name: client
    nodePort: 30000
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
    etcd_cluster: cilium-etcd
  type: NodePort